[package]
name = "diatom"
version = "0.3.1"
edition = "2021"
authors = [ "Terence Ng", "Aoyang Yu" ]
description = "The diatom programming language"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/diatom-lang/diatom.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11.1"
regex = "1.7.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"], optional = true }
ahash = { version = "0.8", default-features = false, features = ["compile-time-rng", "std"] }
ciborium = { version ="0.2.0", optional = true }
reedline = { version = "0.14.0", optional = true }
nu-ansi-term = { version = "0.46.0", optional = true }
crossterm = { version = "0.24.0", optional = true }
clap = { version = "4.0.29", features = ["derive"] }

[features]
default = ["vm", "console"]
vm = ["serde", "ciborium"]
console = ["reedline", "nu-ansi-term", "crossterm"]

[lib]
crate-type = ["cdylib", "rlib"]
