[package]
name = "diatom"
version = "0.1.0"
edition = "2021"
authors = [ "Terence Ng" ]
description = "The diatom programming language"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/TerenceNg03/diatom.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
