[package]
name = "diatom"
version = "0.4.0"
edition = "2021"
authors = [ "Terence Ng", "Aoyang Yu" ]
description = "The diatom programming language"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/diatom-lang/diatom.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codespan-reporting = "0.11.1"
regex = "1.7.0"
lazy_static = "1.4.0"
bimap = "0.6.2"
ahash = { version = "0.8", default-features = false, features = ["compile-time-rng", "std"] }
reedline = { version = "0.14.0", optional = true }
nu-ansi-term = { version = "0.46.0", optional = true }
crossterm = { version = "0.24.0", optional = true }
clap = { version = "4.0.29", features = ["derive"] }
enum_dispatch = "0.3.11"

[features]
default = ["console"]
console = ["reedline", "nu-ansi-term", "crossterm"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "loop"
harness = false
